### ISSUE TITLE
html5lib dep

### ISSUE THREAD

**Issue by papachoco** [NextThought/nti.contentfragments#17]
Jason,

Is there any way we could relax the 

'html5lib[datrie]' 

dependency in the setup.py to simply html5lib and add datrie if the platform is CPython
e.g.

"datrie:platform_python_implementation == 'CPython'": ["datrie"],

The reason is that we will use tensorflow and the latter is using an old version of html5lib. Our project does not use any nti.contentfragments features.

Thanks.

Carlos

**Comment by jamadden** [comment]
I do not understand what you're asking. `html5lib` *already* only installs datrie if needed for CPython. (This project doesn't directly use datrie, IIRC, it just wants it to accelerate html5lib if appropriate.)

**Comment by papachoco** [comment]
basically go from

 install_requires=[
        'setuptools',
        'html5lib[datrie]', 
to

 install_requires=[
        'setuptools',
        'html5lib',

**Comment by jamadden** [comment]
This package almost certainly isn't compatible with versions that don't support that extra, though. (But it's not clear to me what issue that would cause anyway if nothing truly uses this package; unsupported extras are supposed to be simply ignored with a warning)

Can you not just put a version pin in place in your project? Or not even depend on this project in the first place?

**Comment by papachoco** [comment]
Google tensorflow depends on html5lib. It requires  0.9999999 which does not have the datrie extra so I cannot pin the version in buildout

**Comment by jamadden** [comment]
So you have a choice of which package you want to break. 

Why can you not depend on this package?

Why is the missing extra a problem in the first place? It's supposed to be ignored:
```console
]$ pip install html5lib[foobar]
Collecting html5lib[foobar]
    html5lib 1.0.1 does not provide the extra 'foobar'
Collecting webencodings (from html5lib[foobar])
Installing collected packages: webencodings, html5lib
Successfully installed html5lib-1.0.1 webencodings-0.5.1
```

**Comment by papachoco** [comment]
This is running buildout...

I have a pinned version to

[versions]
html5lib = 0.9999999

When I run I get 

Installing eggs.
While:
  Installing eggs.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
...
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/zc.buildout-2.11.5-py2.7.egg/zc/buildout/easy_install.py", line 925, in install
    return installer.install(specs, working_set)
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/zc.buildout-2.11.5-py2.7.egg/zc/buildout/easy_install.py", line 736, in install
    extra_requirements = dist.requires(req.extras)[::-1]
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/setuptools-39.2.0-py2.7.egg/pkg_resources/__init__.py", line 2615, in requires
    "%s has no such extra feature %r" % (self, ext)
UnknownExtra: html5lib 0.9999999 has no such extra feature 'datrie'

**Comment by jamadden** [comment]
I would agree,  like the error says, that’s a bug in buildout. Have you opened an issue?

**Comment by papachoco** [comment]
Not yet

**Comment by papachoco** [comment]
https://github.com/buildout/buildout/issues/457

**Comment by jamadden** [comment]
The buildout maintainers agree this is something we can fix there, so I'll try to work on that; it may take some time. In the meantime I've pushed 1.1.1 to pypi to unblock this.

**Comment by foxrider598** [comment]
- [ ] ~~~~
